// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkje3HHVmersk6wF5xul8jTRs6dQel-wA',
    appId: '1:592182111072:web:9124657b6de53c7108d3fc',
    messagingSenderId: '592182111072',
    projectId: 'kampoeng-steak-ks899',
    authDomain: 'kampoeng-steak-ks899.firebaseapp.com',
    storageBucket: 'kampoeng-steak-ks899.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdYp-PeKbVGglk83fQHQ2HYe5V9NqUteI',
    appId: '1:592182111072:android:5d70a17769c51c30e6cc05',
    messagingSenderId: '592182111072',
    projectId: 'kampoeng-steak-ks899',
    storageBucket: 'kampoeng-steak-ks899.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPQtgmlc80kpSIs8LWSj7qEG-cmzWt3ws',
    appId: '1:592182111072:ios:77884ea86790a88ee6cc05',
    messagingSenderId: '592182111072',
    projectId: 'kampoeng-steak-ks899',
    storageBucket: 'kampoeng-steak-ks899.appspot.com',
    iosBundleId: 'id.co.kampoengsteak',
  );
}
